### PR TITLE
Upgrade runc to 1.1.2 to fix sec issue

### PR DESCRIPTION
**Pull request by josvazg**
This should fix vulnerability issue:
**Default inheritable capabilities for linux container should be empty**

https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/security/dependabot/4

I just added **runc 1.1.2** in the required section on **go.mod** and then did:
```shell
$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Comment by josvazg** [comment]
Error is:
```shell
ginkgo -r -skipPackage test .
Will skip:
  ./test/external
  ./test/features
Failed to compile cmd:

# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/ioctl_linux.go:51:14: undefined: NewIfreq
vendor/golang.org/x/sys/unix/ioctl_linux.go:182:42: undefined: Ifreq
vendor/golang.org/x/sys/unix/ioctl_linux.go:192:46: undefined: ifreqData
```
 
I cannot reproduce locally. @petewall any hints on why is it failing in the CI pipeline?

**Comment by josvazg** [comment]
I tried to test with the docker CI image and I reproduced... a different error!
```shell
  Unexpected error:
      <*errors.errorString | 0xc00007c020>: {
          s: "Failed to build github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes:\n\nError:\nexit status 1\n\nOutput:\nerror obtaining VCS status: exit status 128\n\tUse -buildvcs=false to disable VCS stamping.\n",
      }
      Failed to build github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes:
      
      Error:
      exit status 1
      
      Output:
      error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
      
  occurred
```

Maybe I missed something, right now nothing makes any sense.

**Comment by josvazg** [comment]
072b182 should fix the issue I found, but not sure it will fix the original problem in the CI. In fact the CI as not suffering the VCS issue at all.

**Comment by petewall** [comment]
I attached to the failing job container. Reproduced the error with `make test-units`. Ran `go mod vendor`, which results in four added files:
```
root@7ba6d6b5-3760-4061-46e4-29e90a97a5a8:/tmp/build/28c4f8c4/source# git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	vendor/golang.org/x/sys/unix/ifreq_linux.go
	vendor/golang.org/x/sys/unix/sysvshm_linux.go
	vendor/golang.org/x/sys/unix/sysvshm_unix.go
	vendor/golang.org/x/sys/unix/sysvshm_unix_other.go
```

First time running `make test-units` resulted in:
```
    rewrite_action_test.go:183: the resulting Chart does not match the fixture. got=45f58f9150621b486e2d8c9fd2bc88db4815d7046cc4ac299d4e775e9a202776, want=943597a0743db1b02205ecd60a17f71a00b155c1619e21142c0c28eb17fe3e7c
```
but the second time, the test passed.

So, it seems to be a difference in Mac and linux vendor files.

**Comment by petewall** [comment]
Actually, running `go mod vendor` on my Mac added those files, too. Committed and updated the PR. I'll check the test results.

**Review by petewall — APPROVED** [review]
LGTM

**Pull request merged**
