### PR TITLE
feat(ci): Rebase error handling

### PR DESCRIPTION
**Pull request by migmartri**
When there is a merge conflict, the PR is now marked as failed 

Signed-off-by: Miguel Martinez Trivino <mtrivino@vmware.com>

### CODE REVIEW

**Review by petewall — COMMENTED** [review]
Seems fine.

Try it out?
* Download fly cli
* `fly login --target <target name> --concourse-url https://runway-ci.eng.vmware.com --team-name tanzu-isv-engineering`
* `make set-pipeline`

**Comment by migmartri** [comment]
> * `fly login --target <target name> --concourse-url https://runway-ci.eng.vmware.com --team-name tanzu-isv-engineering`

Thanks for the pointer.

I might have not permissions to do so?

```
apply configuration? [yN]: y
error: forbidden
```

**Comment by petewall** [comment]
> > * `fly login --target <target name> --concourse-url https://runway-ci.eng.vmware.com --team-name tanzu-isv-engineering`
> 
> Thanks for the pointer.
> 
> I might have not permissions to do so?
> 
> ```
> apply configuration? [yN]: y
> error: forbidden
> ```

Oh, I should have specified. While you can replace `<target name>` with some nickname that you set, I'm using `tie` in the Makefile. You can see your existing targets using `fly targets`. Make sure you're using `tie`.

If that's not the case, I can help. I checked and you should have all the permissions you need on `https://runway.eng.vmware.com/`

**Comment by migmartri** [comment]
> > > * `fly login --target <target name> --concourse-url https://runway-ci.eng.vmware.com --team-name tanzu-isv-engineering`
> > 
> > 
> > Thanks for the pointer.
> > I might have not permissions to do so?
> > ```
> > apply configuration? [yN]: y
> > error: forbidden
> > ```
> 
> Oh, I should have specified. While you can replace `<target name>` with some nickname that you set, I'm using `tie` in the Makefile. You can see your existing targets using `fly targets`. Make sure you're using `tie`.
> 
> If that's not the case, I can help. I checked and you should have all the permissions you need on `https://runway.eng.vmware.com/`

yeah, I used `tie` since I saw it hardcoded in the Makefile and now it worked, did you change anything? 

Either way, thanks!!

**Comment by petewall** [comment]
> did you change anything?

I changed you from an "operator" to an "owner". Maybe only owners can `set-pipeline`'s?

**Comment by migmartri** [comment]
In the end, sending an `put` at the beginning of the pipeline, even before the code is fetched is not possible https://github.com/telia-oss/github-pr-resource/issues/210

So this code in practice just adds merge error handling.

**Comment by migmartri** [comment]
@petewall ptal, I [tested](https://runway-ci.eng.vmware.com/teams/tanzu-isv-engineering/pipelines/relok8s/jobs/test-pull-request/builds/33) the change and seems to work as expected.

Thanks!

**Review by petewall — APPROVED** [review]
LGTM

**Comment by migmartri** [comment]
> > did you change anything?
> 
> I changed you from an "operator" to an "owner". Maybe only owners can `set-pipeline`'s?

That made the trick, thanks!

**Pull request merged**
